services:
  postgres:
    image: postgres:15
    container_name: country-votes-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: country-votes
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: country-votes-backend
    ports:
      - "4041:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    entrypoint:
      [
        "sh",
        "-c",
        "npx prisma migrate deploy && npx prisma generate && npm run start:dev",
      ]
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: country-votes-frontend
    ports:
      - "3031:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
